###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mariadb:
        container_name: test-main-backend-mariadb
        image: 'mariadb:10.6'
        working_dir: /application
        volumes:
            - './:/application'
            - './storage/mysql-data:/var/lib/mysql/' #Save db-data to disc
        environment:
            - MYSQL_ROOT_PASSWORD=333333
            - MYSQL_DATABASE=test
            - MYSQL_USER=test
            - MYSQL_PASSWORD=333333
        ports:
            - '8891:3306'

    webserver:
        container_name: test-main-backend-webserver
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8888:80'

    php-fpm:
        container_name: test-main-backend-php-fpm
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - './:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
